site_name: Awesome Software Architecture
site_url: https://awesome-architecture.com
site_description: Curated list of awesome articles and resources to learn and practice about software architecture, patterns and principles.
docs_dir: 
repo_name: mehdihadeli/awesome-software-architecture
repo_url: https://github.com/mehdihadeli/awesome-software-architecture
edit_uri: edit/main/docs/
theme: 
  name: material 
  #https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
  features:
    - navigation.instant
    - navigation.tracking
    - toc.integrate 
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  prev_next_buttons_location: both
  navigation_depth: 4
  titles_only: False
  sticky_navigation: True
markdown_extensions:
  - smarty
  - sane_lists
  - fenced_code
  - meta
  - admonition
  - attr_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - codehilite
  - footnotes
  - toc:
      permalink: true

nav:
- Software Architecture: software-architecture.md
- Actor Model Architecture: 
  - Actor Model Architecture: actor-model-architecture/actor-model-architecture.md
  - Akka .NET: actor-model-architecture/akka-net.md
  - Orleans: actor-model-architecture/orleans.md
  - Protoactor: actor-model-architecture/protoactor.md
- Algorithms: algorithm.md
- Clean Architecture: clean-architecture.md
- Onion Architecture: onion-architecture.md
- Hexagonal Architecture: hexagonal-architecture.md
- Vertical Slice Architecture: vertical-slice-architecture.md
- Event Driven Architecture: event-driven-architecture.md
- Service Oriented Architecture: service-oriented-architecture.md
- Domain Driven Design: 
  - Domain Driven Design: domain-driven-design/domain-driven-design.md
  - Domain: domain-driven-design/domain.md
  - Aggregation: domain-driven-design/aggregation.md
  - Anemic Domain Model: domain-driven-design/anemic-domain-model.md
  - Rich Domain Model: domain-driven-design/rich-domain-model.md
  - Application Service: domain-driven-design/application-service.md
  - Bounded Context: domain-driven-design/bounded-context.md
  - Domain Events: domain-driven-design/domain-events.md
  - Integration Events: domain-driven-design/integration-event.md
  - Primitive obsession: domain-driven-design/domain-primitives.md
  - Domain Service: domain-driven-design/domain-service.md
  - Enums: domain-driven-design/enums.md
  - Exception And Validation: domain-driven-design/exception-and-validation.md
  - Infrastructure: domain-driven-design/infrastructure.md
  - Mapping: domain-driven-design/mapping.md
  - Persistence Ignorance: architectural-design-principles/persistence-ignorance.md
  - Strategic Design Patterns: domain-driven-design/strategic-design-patterns.md
  - Tactical Design Patterns: domain-driven-design/tactical-design-patterns.md
  - Value Objects: domain-driven-design/value-objects.md
  - Event Sourcing: domain-driven-design/event-sourcing.md
  - ORMs:
    - Entity Framework: domain-driven-design/orm/ef.md   
- Data Driven Design: data-driven-design.md
- CQRS: cqrs.md
- Modular Monolith: modular-monolith.md
- Architectural Design Principles: 
  - Architectural Design Principles: architectural-design-principles/architectural-design-principles.md
  - CAP Theorem: architectural-design-principles/cap.md
  - Cohesion: architectural-design-principles/cohesion.md
  - Command Query Separation - CQS: architectural-design-principles/cqs.md
  - Coupling: architectural-design-principles/coupling.md
  - Crosscutting Concerns: architectural-design-principles/crosscutting-concerns.md
  - Dependency Inversion: architectural-design-principles/dependency-inversion.md
  - Donot Repeat Yourself - DRY: architectural-design-principles/dry.md
  - Encapsulation: architectural-design-principles/encapsulation.md
  - Fail-Fast: architectural-design-principles/fail-fast.md
  - Favor Composition over Inheritance: architectural-design-principles/favor-composition-over-inheritance.md
  - GRASP: architectural-design-principles/grasp.md
  - Interface Segregation: architectural-design-principles/interface-segregation.md
  - Inversion of Control: architectural-design-principles/inversion-control.md
  - Keep It Simple - KISS: architectural-design-principles/kiss.md
  - Open/Closed Principle: architectural-design-principles/open-closed-principle.md
  - Persistence Ignorance: architectural-design-principles/persistence-ignorance.md
  - Single Responsibility: architectural-design-principles/single-responsibility.md
  - SOLID: architectural-design-principles/solid.md
  - YAGNI: architectural-design-principles/yagni.md
- Design Patterns: 
  - Builder Pattern: design-patterns/builder.md
  - Design Patterns: design-patterns/design-patterns.md
  - Singleton: design-patterns/singleton.md
  - Decorator Pattern: design-patterns/decorator-pattern.md
  - Specification Pattern: design-patterns/specification-pattern.md
  - Repository Pattern: design-patterns/repository-pattern.md
  - REPR: design-patterns/repr.md
  - Query Object Pattern: design-patterns/query-object-pattern.md
  - Factory Pattern: design-patterns/factory-pattern.md
  - Strategy Pattern: design-patterns/strategy-pattern.md
  - State Pattern: design-patterns/state-pattern.md
  - Adapter Pattern: design-patterns/adapter-pattern.md
  - Command Message Pattern: design-patterns/command-message-pattern.md
  - Observer Pattern: design-patterns/observer.md
  - Chain Of Responsibility: design-patterns/chain-of-responsibility.md
  - AutoPilot Pattern: design-patterns/autopilot.md
  - Transaction Script Pattern: design-patterns/transaction-script-pattern.md
- Cloud Design Patterns: 
  - Cloud Design Patterns: cloud-design-patterns/cloud-design-patterns.md
  - Ambassador Pattern: cloud-design-patterns/ambassador-pattern.md
  - Sidecar Pattern: cloud-design-patterns/sidecar.md
  - Anti Corruption Layer Pattern: cloud-design-patterns/anti-corruption-layer-pattern.md
  - Bulkhead Pattern: cloud-design-patterns/bulkhead-pattern.md
  - Circuit Breaker Pattern: cloud-design-patterns/circuit-breaker.md
  - Exactly One Delivery: cloud-design-patterns/exactly-one-delivery.md
  - Gateway Aggregation: cloud-design-patterns/gateway-aggregation.md
  - Gateway Pattern: cloud-design-patterns/gateway-pattern.md
  - Outbox Pattern: cloud-design-patterns/outbox-pattern.md
  - Inbox Pattern: cloud-design-patterns/inbox-pattern.md
  - Strangler Fig Pattern: cloud-design-patterns/strangler-fig-pattern.md
  - Backends for Frontends: cloud-design-patterns/bff.md
- Cloud Best Practices: cloud-best-practices.md
- Cloud Native: cloud-native.md
- Platform as a Service:
  - Rancher: paas/rancher.md
  - OpenShift: paas/openshift.md
  - Heroku: paas/heroku.md
  - Netlify: paas/netlify.md
- Infrastructure as a Service:
  - Infrastructure as a Service: iaas/iaas.md
  - Terraform: iaas/terraform.md
  - Pulumi: iaas/pulumi.md
  - Ansible: iaas/ansible.md
  - Nomad: iaas/nomad.md
- DevOps:
  - Docker: 
    - Docker: devops/docker/docker.md
    - Docker Compose: devops/docker/docker-compose.md
  - Containerd: devops/containerd.md
  - Kubernetes: 
    - Kubernetes: devops/kubernetes/kubernetes.md
    - Deployment Strategies: devops/kubernetes/deployment-strategies.md
    - Deployment Tools: 
        - Argo-CD: devops/kubernetes/deployment-tools/argo-cd.md
        - Helm: devops/kubernetes/deployment-tools/helm.md
        - Kustomize: devops/kubernetes/deployment-tools/kustomize.md
        - Kubernetes Operator: devops/kubernetes/deployment-tools/kubernetes-operator.md
        - Jenkins: devops/kubernetes/deployment-tools/jenkins.md
    - Ingress Controller: 
        - Ingress Controller: devops/kubernetes/ingress-controller.md
        - Nginx Ingress: devops/kubernetes/nginx-ingress.md
        - Traefik Ingress: devops/kubernetes/traefik-ingress.md
    - Other Tools: 
        - K3s: devops/kubernetes/other-tools/k3s.md
        - Telepresence: devops/kubernetes/other-tools/telepresence.md
        - Telepresence: devops/kubernetes/other-tools/telepresence.md
        - Garden: devops/kubernetes/other-tools/garden.md
        - Tilt: devops/kubernetes/other-tools/tilt.md
  - CI/CD:
    - Azure DevOps: devops/ci-cd/azure-devops.md
    - Github Actions: devops/ci-cd/github-actions.md
    - Jenkins: devops/ci-cd/jenkins.md
- Reverse Proxy & Load Balancing:
    - Reverse Proxy: reverse-proxy-lb/reverse-proxy.md
    - Load Balancing: reverse-proxy-lb/load-balancing.md
    - Envoy: reverse-proxy-lb/envoy.md
    - YARP: reverse-proxy-lb/yarp.md
    - HAProxy: reverse-proxy-lb/haproxy.md
    - Fabio: reverse-proxy-lb/fabio.md
    - MetalLB: reverse-proxy-lb/metallb.md
    - Nginx: reverse-proxy-lb/nginx.md
    - Traefik: reverse-proxy-lb/traefik.md
- Service Discovery & Registry: 
    - Service Discovery & Registry: service-discovery/service-discovery.md
    - Consul: service-discovery/consul.md
    - Eureka: service-discovery/eureka.md
- Service Mesh: 
  - Service Mesh: service-mesh/service-mesh.md
  - Istio: service-mesh/istio.md
  - Consul & Consul Connect: service-discovery/consul.md
  - Maesh: service-mesh/maesh.md
  - Linkerd: service-mesh/linkerd.md
- Object Oriented Design: object-oriented-design.md
- Systems Design: 
  - Systems Design: systems-design/systems-design.md
  - Consistent Hashing: systems-design/consistent-hash.md
- Scaling: scaling.md
- Back Pressure: back-pressure.md
- Clean Code: clean-code.md
- Abstraction: abstraction.md
- Design Best Practices: 
  - Design Best Practices: design-best-practices/design-best-practices.md
  - 12 Factor: design-best-practices/12-factor.md
  - Strongly Type Ids & Snowflake: design-best-practices/strongly-typed-ids.md
  - Thin Controllers: design-best-practices/thin-controllers.md
- Anti Patterns: 
  - Anti Patterns: anti-patterns/anti-patterns.md
  - Big Ball of Mud: anti-patterns/big-ball-of-mud.md
  - Code Smells: anti-patterns/code-smells.md
  - Partial/Optional Object: anti-patterns/partial-object.md
  - God Object: anti-patterns/god-object.md
  - Static Cling: anti-patterns/static-cling.md
- Eventual Consistency: eventual-consistency.md
- Messaging:
  - Messaging: messaging/messaging.md
  - Change Data Capture (CDC): messaging/change-data-capture.md
  - Async APIs Documentation: messaging/async-api-documentation.md
  - Kafka: messaging/kafka.md
  - RabbitMQ: messaging/rabbitmq.md
  - Azure Service Bus: azure/messaging/azure-service-bus.md
  - NATS: messaging/nats.md
- Distributed Transactions & Saga: distributed-transactions.md
- Distributed Locking: distributed-locking.md
- Eventual Consistency: eventual-consistency.md
- RESTful API Design: rest.md
- gRPC: grpc.md
- Caching: caching.md
- Functional Programming: functional.md
- Concurrency: concurrency.md
- Sharding: sharding.md
- Refactoring: refactoring.md
- NoSQL:
  - NoSQL: nosql/nosql.md
  - CosmosDB: nosql/cosmosdb.md
  - DocumentDB: nosql/documentdb.md
  - MongoDB: nosql/mongodb.md
  - Postgresql: nosql/postgresql.md
- Relational Database:
  - Relational Database: relational/relational-database.md
  - Postgresql: relational/postgres.md
  - SQL: relational/sql.md
- Azure Cloud:
  - Azure Cloud: azure/azure-cloud.md
  - Azure API Management: azure/azure-api-management.md
  - Azure App Service: azure/azure-app-service.md
  - Azure App Service Plan: azure/azure-app-service-plan.md
  - Azure Functions / Azure Serverless: azure/azure-functions.md
  - Azure Kubernetes Service (AKS): azure/aks.md
  - Azure Load Balancing: azure/azure-load-balancing.md
  - Azure Logic App: azure/azure-logic-app.md
  - Azure Resource & Resource Group: azure/azure-resource.md
  - Azure App Configuration: azure/azure-configuration.md
  - Azure Messaging:
    - Azure Messaging: azure/messaging/messaging.md
    - Azure Event Grid: azure/messaging/azure-event-grid.md
    - Azure Event Hub: azure/messaging/azure-event-hub.md
    - Azure Queue: azure/messaging/azure-queue.md
    - Azure Service Bus: azure/messaging/azure-service-bus.md
    - Azure Web Pub/Sub: azure/messaging/azure-web-pub-sub.md
  - Azure Resource Manager (ARM): azure/azure-resource-manager.md
  - Azure Sequrity: 
    - Azure Active Directory (Azure AD): azure/azure-active-directory.md
    - Azure Key Vault: azure/azure-key-vault.md
  - Azure SQL: azure/azure-sql.md
  - Azure No-SQL: 
       Azure No-SQL: azure/nosql/azure-nosql.md
       Azure CosmosDB: azure/nosql/cosmosdb.md
  - Azure Storage:
    - Azure Storage: azure/storage/storage.md
    - Azure Blob: azure/storage/blob.md
    - Azure Queue: azure/storage/queue.md
    - Azure Table: azure/storage/table.md
    - Azure File: azure/storage/file.md
  - Azure Template: azure/azure-template.md
- Modeling: 
  - Modeling: modeling/modeling.md
  - Event Storming: modeling/event-storming.md
  - Event Modeling: modeling/event-modeling.md
  - Domain Stroytelling: modeling/domain-stroytelling.md
  - Architecture Diagram: modeling/architecture-diagram.md
  - Class Diagram: modeling/class-diagram.md
  - Component Diagram: modeling/component-diagram.md
  - Conceptual Diagram: modeling/conceptual-diagram.md
  - Conceptual Modeling: modeling/conceptual-modeling.md
  - Data Modeling Notations: modeling/data-modeling-notations.md
  - ER Diagrams: modeling/er-diagrams.md
  - Logical Modeling: modeling/logical-modeling.md
  - Physical Modeling: modeling/physical-modeling.md
  - Relationship: modeling/relationship.md
  - Tools: modeling/tools.md
  - Use Case Diagram: modeling/use-case-diagram.md
- AI: ai.md
- Open Source: open-source.md
- Code Review: code-review.md
- Interview: interview.md
- Architecture Decision Records (ADR): adr.md
- Micro-Frontend: micro-frontend.md
- Others: others.md


copyright: 2023 <a href="https://github.com/mehdihadeli">Mehdi Hadeli</a>.
#remote_branch: gh-pages 
#remote_name: origin
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mehdi_hadeli
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mehdihadeli
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mehdihadeli
